### ISSUE TITLE
Outdated/unsupported dependencies.

### ISSUE THREAD

**Issue by mainakdev15** [debdip-banerjee/react-formbuilder-lib#1]
- react-formbuilder-lib@1.0.4 requires **typescript@^4.9.5**, but latest NextJS/Vite projects use **typescript@5.4.5.**
- For each deprecated package, you can search for its latest version or an alternative package. Some replacements are suggested in the warnings
```powershell
npm install glob@latest
```
- Regularly run npm outdated to check for outdated packages.
- Periodically run npm audit to ensure there are no new vulnerabilities.
- Consider using tools like renovate or dependabot to automatically keep dependencies up-to-date.

**Comment by debdip-banerjee** [comment]
noted. will release in next version shortly.
